=== raml-apis/StackExchange/schemas/badges.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "award_count": {
        "required": false,
        "type": "integer"
      },
      "badge_id": {
        "required": false,
        "type": "integer"
      },
      "badge_type": {
        "required": false,
        "type": "string"
      },
      "description": {
        "required": false,
        "type": "string"
      },
      "link": {
        "required": false,
        "type": "string"
      },
      "name": {
        "required": false,
        "type": "string"
      },
      "rank": {
        "required": false,
        "type": "string"
      },
      "user": {
        "required": false,
        "type": "object",
        "properties": {
          "accept_rate": {
            "required": false,
            "type": "integer"
          },
          "badge_counts": {
            "required": false,
            "type": "object",
            "properties": {
              "bronze": {
                "required": false,
                "type": "integer"
              },
              "gold": {
                "required": false,
                "type": "integer"
              },
              "silver": {
                "required": false,
                "type": "integer"
              }
            }
          },
          "display_name": {
            "required": false,
            "type": "string"
          },
          "link": {
            "required": false,
            "type": "string"
          },
          "profile_image": {
            "required": false,
            "type": "string"
          },
          "reputation": {
            "required": false,
            "type": "integer"
          },
          "user_id": {
            "required": false,
            "type": "integer"
          },
          "user_type": {
            "required": false,
            "type": "string"
          }
        }
      }
    }
  }
}

=== raml-apis/StackExchange/examples/badges.json
[
  {
    "award_count": 1,
    "badge_id": 1,
    "badge_type": "some string",
    "description": "some string",
    "link": "some string",
    "name": "some string",
    "rank": "some string",
    "user": {
      "accept_rate": 1,
      "badge_counts": {
        "bronze": 1,
        "gold": 1,
        "silver": 1
      },
      "display_name": "some string",
      "link": "some string",
      "profile_image": "some string",
      "reputation": 1,
      "user_id": 1,
      "user_type": "some string"
    }
  }
]
