=== raml-apis/StackExchange/schemas/inbox_items.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "answer_id": {
        "required": false,
        "type": "integer"
      },
      "body": {
        "required": false,
        "type": "string"
      },
      "comment_id": {
        "required": false,
        "type": "integer"
      },
      "creation_date": {
        "required": false,
        "type": "integer"
      },
      "is_unread": {
        "required": false,
        "type": "boolean"
      },
      "item_type": {
        "required": false,
        "type": "string"
      },
      "link": {
        "required": false,
        "type": "string"
      },
      "question_id": {
        "required": false,
        "type": "integer"
      },
      "site": {
        "required": false,
        "type": "object",
        "properties": {
          "aliases": {
            "required": false,
            "type": "array"
          },
          "api_site_parameter": {
            "required": false,
            "type": "string"
          },
          "audience": {
            "required": false,
            "type": "string"
          },
          "closed_beta_date": {
            "required": false,
            "type": "integer"
          },
          "favicon_url": {
            "required": false,
            "type": "string"
          },
          "high_resolution_icon_url": {
            "required": false,
            "type": "string"
          },
          "icon_url": {
            "required": false,
            "type": "string"
          },
          "launch_date": {
            "required": false,
            "type": "integer"
          },
          "logo_url": {
            "required": false,
            "type": "string"
          },
          "markdown_extensions": {
            "required": false,
            "type": "array"
          },
          "name": {
            "required": false,
            "type": "string"
          },
          "open_beta_date": {
            "required": false,
            "type": "integer"
          },
          "related_sites": {
            "required": false,
            "type": "array"
          },
          "site_state": {
            "required": false,
            "type": "string"
          },
          "site_type": {
            "required": false,
            "type": "string"
          },
          "site_url": {
            "required": false,
            "type": "string"
          },
          "styling": {
            "required": false,
            "type": "object",
            "properties": {
              "link_color": {
                "required": false,
                "type": "string"
              },
              "tag_background_color": {
                "required": false,
                "type": "string"
              },
              "tag_foreground_color": {
                "required": false,
                "type": "string"
              }
            }
          },
          "twitter_account": {
            "required": false,
            "type": "string"
          }
        }
      },
      "title": {
        "required": false,
        "type": "string"
      }
    }
  }
}

=== raml-apis/StackExchange/examples/inbox_items.json
[
  {
    "answer_id": 1,
    "body": "some string",
    "comment_id": 1,
    "creation_date": 1,
    "is_unread": true,
    "item_type": "some string",
    "link": "some string",
    "question_id": 1,
    "site": {
      "aliases": [
      ],
      "api_site_parameter": "some string",
      "audience": "some string",
      "closed_beta_date": 1,
      "favicon_url": "some string",
      "high_resolution_icon_url": "some string",
      "icon_url": "some string",
      "launch_date": 1,
      "logo_url": "some string",
      "markdown_extensions": [
      ],
      "name": "some string",
      "open_beta_date": 1,
      "related_sites": [
      ],
      "site_state": "some string",
      "site_type": "some string",
      "site_url": "some string",
      "styling": {
        "link_color": "some string",
        "tag_background_color": "some string",
        "tag_foreground_color": "some string"
      },
      "twitter_account": "some string"
    },
    "title": "some string"
  }
]
