=== raml-apis/StackExchange/schemas/info_object.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "object",
  "properties": {
    "answers_per_minute": {
      "required": false,
      "type": "number"
    },
    "api_revision": {
      "required": false,
      "type": "string"
    },
    "badges_per_minute": {
      "required": false,
      "type": "number"
    },
    "new_active_users": {
      "required": false,
      "type": "integer"
    },
    "questions_per_minute": {
      "required": false,
      "type": "number"
    },
    "site": {
      "required": false,
      "type": "object",
      "properties": {
        "aliases": {
          "required": false,
          "type": "array"
        },
        "api_site_parameter": {
          "required": false,
          "type": "string"
        },
        "audience": {
          "required": false,
          "type": "string"
        },
        "closed_beta_date": {
          "required": false,
          "type": "integer"
        },
        "favicon_url": {
          "required": false,
          "type": "string"
        },
        "high_resolution_icon_url": {
          "required": false,
          "type": "string"
        },
        "icon_url": {
          "required": false,
          "type": "string"
        },
        "launch_date": {
          "required": false,
          "type": "integer"
        },
        "logo_url": {
          "required": false,
          "type": "string"
        },
        "markdown_extensions": {
          "required": false,
          "type": "array"
        },
        "name": {
          "required": false,
          "type": "string"
        },
        "open_beta_date": {
          "required": false,
          "type": "integer"
        },
        "related_sites": {
          "required": false,
          "type": "array"
        },
        "site_state": {
          "required": false,
          "type": "string"
        },
        "site_type": {
          "required": false,
          "type": "string"
        },
        "site_url": {
          "required": false,
          "type": "string"
        },
        "styling": {
          "required": false,
          "type": "object",
          "properties": {
            "link_color": {
              "required": false,
              "type": "string"
            },
            "tag_background_color": {
              "required": false,
              "type": "string"
            },
            "tag_foreground_color": {
              "required": false,
              "type": "string"
            }
          }
        },
        "twitter_account": {
          "required": false,
          "type": "string"
        }
      }
    },
    "total_accepted": {
      "required": false,
      "type": "integer"
    },
    "total_answers": {
      "required": false,
      "type": "integer"
    },
    "total_badges": {
      "required": false,
      "type": "integer"
    },
    "total_comments": {
      "required": false,
      "type": "integer"
    },
    "total_questions": {
      "required": false,
      "type": "integer"
    },
    "total_unanswered": {
      "required": false,
      "type": "integer"
    },
    "total_users": {
      "required": false,
      "type": "integer"
    },
    "total_votes": {
      "required": false,
      "type": "integer"
    }
  }
}

=== raml-apis/StackExchange/examples/info_object.json
{
  "answers_per_minute": 1.0,
  "api_revision": "some string",
  "badges_per_minute": 1.0,
  "new_active_users": 1,
  "questions_per_minute": 1.0,
  "site": {
    "aliases": [
    ],
    "api_site_parameter": "some string",
    "audience": "some string",
    "closed_beta_date": 1,
    "favicon_url": "some string",
    "high_resolution_icon_url": "some string",
    "icon_url": "some string",
    "launch_date": 1,
    "logo_url": "some string",
    "markdown_extensions": [
    ],
    "name": "some string",
    "open_beta_date": 1,
    "related_sites": [
    ],
    "site_state": "some string",
    "site_type": "some string",
    "site_url": "some string",
    "styling": {
      "link_color": "some string",
      "tag_background_color": "some string",
      "tag_foreground_color": "some string"
    },
    "twitter_account": "some string"
  },
  "total_accepted": 1,
  "total_answers": 1,
  "total_badges": 1,
  "total_comments": 1,
  "total_questions": 1,
  "total_unanswered": 1,
  "total_users": 1,
  "total_votes": 1
}
