=== raml-apis/StackExchange/schemas/network_users.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "account_id": {
        "required": false,
        "type": "integer"
      },
      "answer_count": {
        "required": false,
        "type": "integer"
      },
      "badge_counts": {
        "required": false,
        "type": "object",
        "properties": {
          "bronze": {
            "required": false,
            "type": "integer"
          },
          "gold": {
            "required": false,
            "type": "integer"
          },
          "silver": {
            "required": false,
            "type": "integer"
          }
        }
      },
      "creation_date": {
        "required": false,
        "type": "integer"
      },
      "last_access_date": {
        "required": false,
        "type": "integer"
      },
      "question_count": {
        "required": false,
        "type": "integer"
      },
      "reputation": {
        "required": false,
        "type": "integer"
      },
      "site_name": {
        "required": false,
        "type": "string"
      },
      "site_url": {
        "required": false,
        "type": "string"
      },
      "top_answers": {
        "required": false,
        "type": "array"
      },
      "top_questions": {
        "required": false,
        "type": "array"
      },
      "user_id": {
        "required": false,
        "type": "integer"
      },
      "user_type": {
        "required": false,
        "type": "string"
      }
    }
  }
}

=== raml-apis/StackExchange/examples/network_users.json
[
  {
    "account_id": 1,
    "answer_count": 1,
    "badge_counts": {
      "bronze": 1,
      "gold": 1,
      "silver": 1
    },
    "creation_date": 1,
    "last_access_date": 1,
    "question_count": 1,
    "reputation": 1,
    "site_name": "some string",
    "site_url": "some string",
    "top_answers": [
    ],
    "top_questions": [
    ],
    "user_id": 1,
    "user_type": "some string"
  }
]
