=== raml-apis/StackExchange/schemas/posts.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "body": {
        "required": false,
        "type": "string"
      },
      "body_markdown": {
        "required": false,
        "type": "string"
      },
      "comment_count": {
        "required": false,
        "type": "integer"
      },
      "comments": {
        "required": false,
        "type": "array"
      },
      "creation_date": {
        "required": false,
        "type": "integer"
      },
      "down_vote_count": {
        "required": false,
        "type": "integer"
      },
      "downvoted": {
        "required": false,
        "type": "boolean"
      },
      "last_activity_date": {
        "required": false,
        "type": "integer"
      },
      "last_edit_date": {
        "required": false,
        "type": "integer"
      },
      "last_editor": {
        "required": false,
        "type": "object",
        "properties": {
          "accept_rate": {
            "required": false,
            "type": "integer"
          },
          "badge_counts": {
            "required": false,
            "type": "object",
            "properties": {
              "bronze": {
                "required": false,
                "type": "integer"
              },
              "gold": {
                "required": false,
                "type": "integer"
              },
              "silver": {
                "required": false,
                "type": "integer"
              }
            }
          },
          "display_name": {
            "required": false,
            "type": "string"
          },
          "link": {
            "required": false,
            "type": "string"
          },
          "profile_image": {
            "required": false,
            "type": "string"
          },
          "reputation": {
            "required": false,
            "type": "integer"
          },
          "user_id": {
            "required": false,
            "type": "integer"
          },
          "user_type": {
            "required": false,
            "type": "string"
          }
        }
      },
      "link": {
        "required": false,
        "type": "string"
      },
      "owner": {
        "required": false,
        "type": "object",
        "properties": {
          "accept_rate": {
            "required": false,
            "type": "integer"
          },
          "badge_counts": {
            "required": false,
            "type": "object",
            "properties": {
              "bronze": {
                "required": false,
                "type": "integer"
              },
              "gold": {
                "required": false,
                "type": "integer"
              },
              "silver": {
                "required": false,
                "type": "integer"
              }
            }
          },
          "display_name": {
            "required": false,
            "type": "string"
          },
          "link": {
            "required": false,
            "type": "string"
          },
          "profile_image": {
            "required": false,
            "type": "string"
          },
          "reputation": {
            "required": false,
            "type": "integer"
          },
          "user_id": {
            "required": false,
            "type": "integer"
          },
          "user_type": {
            "required": false,
            "type": "string"
          }
        }
      },
      "post_id": {
        "required": false,
        "type": "integer"
      },
      "post_type": {
        "required": false,
        "type": "string"
      },
      "score": {
        "required": false,
        "type": "integer"
      },
      "share_link": {
        "required": false,
        "type": "string"
      },
      "title": {
        "required": false,
        "type": "string"
      },
      "up_vote_count": {
        "required": false,
        "type": "integer"
      },
      "upvoted": {
        "required": false,
        "type": "boolean"
      }
    }
  }
}

=== raml-apis/StackExchange/examples/posts.json
[
  {
    "body": "some string",
    "body_markdown": "some string",
    "comment_count": 1,
    "comments": [
    ],
    "creation_date": 1,
    "down_vote_count": 1,
    "downvoted": true,
    "last_activity_date": 1,
    "last_edit_date": 1,
    "last_editor": {
      "accept_rate": 1,
      "badge_counts": {
        "bronze": 1,
        "gold": 1,
        "silver": 1
      },
      "display_name": "some string",
      "link": "some string",
      "profile_image": "some string",
      "reputation": 1,
      "user_id": 1,
      "user_type": "some string"
    },
    "link": "some string",
    "owner": {
      "accept_rate": 1,
      "badge_counts": {
        "bronze": 1,
        "gold": 1,
        "silver": 1
      },
      "display_name": "some string",
      "link": "some string",
      "profile_image": "some string",
      "reputation": 1,
      "user_id": 1,
      "user_type": "some string"
    },
    "post_id": 1,
    "post_type": "some string",
    "score": 1,
    "share_link": "some string",
    "title": "some string",
    "up_vote_count": 1,
    "upvoted": true
  }
]
