=== raml-apis/StackExchange/schemas/questions.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "accepted_answer_id": {
        "required": false,
        "type": "integer"
      },
      "answer_count": {
        "required": false,
        "type": "integer"
      },
      "answers": {
        "required": false,
        "type": "array"
      },
      "body": {
        "required": false,
        "type": "string"
      },
      "body_markdown": {
        "required": false,
        "type": "string"
      },
      "bounty_amount": {
        "required": false,
        "type": "integer"
      },
      "bounty_closes_date": {
        "required": false,
        "type": "integer"
      },
      "bounty_user": {
        "required": false,
        "type": "object",
        "properties": {
          "accept_rate": {
            "required": false,
            "type": "integer"
          },
          "badge_counts": {
            "required": false,
            "type": "object",
            "properties": {
              "bronze": {
                "required": false,
                "type": "integer"
              },
              "gold": {
                "required": false,
                "type": "integer"
              },
              "silver": {
                "required": false,
                "type": "integer"
              }
            }
          },
          "display_name": {
            "required": false,
            "type": "string"
          },
          "link": {
            "required": false,
            "type": "string"
          },
          "profile_image": {
            "required": false,
            "type": "string"
          },
          "reputation": {
            "required": false,
            "type": "integer"
          },
          "user_id": {
            "required": false,
            "type": "integer"
          },
          "user_type": {
            "required": false,
            "type": "string"
          }
        }
      },
      "can_close": {
        "required": false,
        "type": "boolean"
      },
      "can_flag": {
        "required": false,
        "type": "boolean"
      },
      "close_vote_count": {
        "required": false,
        "type": "integer"
      },
      "closed_date": {
        "required": false,
        "type": "integer"
      },
      "closed_details": {
        "required": false,
        "type": "object",
        "properties": {
          "by_users": {
            "required": false,
            "type": "array"
          },
          "description": {
            "required": false,
            "type": "string"
          },
          "on_hold": {
            "required": false,
            "type": "boolean"
          },
          "original_questions": {
            "required": false,
            "type": "array"
          },
          "reason": {
            "required": false,
            "type": "string"
          }
        }
      },
      "closed_reason": {
        "required": false,
        "type": "string"
      },
      "comment_count": {
        "required": false,
        "type": "integer"
      },
      "comments": {
        "required": false,
        "type": "array"
      },
      "community_owned_date": {
        "required": false,
        "type": "integer"
      },
      "creation_date": {
        "required": false,
        "type": "integer"
      },
      "delete_vote_count": {
        "required": false,
        "type": "integer"
      },
      "down_vote_count": {
        "required": false,
        "type": "integer"
      },
      "downvoted": {
        "required": false,
        "type": "boolean"
      },
      "favorite_count": {
        "required": false,
        "type": "integer"
      },
      "favorited": {
        "required": false,
        "type": "boolean"
      },
      "is_answered": {
        "required": false,
        "type": "boolean"
      },
      "last_activity_date": {
        "required": false,
        "type": "integer"
      },
      "last_edit_date": {
        "required": false,
        "type": "integer"
      },
      "last_editor": {
        "required": false,
        "type": "object",
        "properties": {
          "accept_rate": {
            "required": false,
            "type": "integer"
          },
          "badge_counts": {
            "required": false,
            "type": "object",
            "properties": {
              "bronze": {
                "required": false,
                "type": "integer"
              },
              "gold": {
                "required": false,
                "type": "integer"
              },
              "silver": {
                "required": false,
                "type": "integer"
              }
            }
          },
          "display_name": {
            "required": false,
            "type": "string"
          },
          "link": {
            "required": false,
            "type": "string"
          },
          "profile_image": {
            "required": false,
            "type": "string"
          },
          "reputation": {
            "required": false,
            "type": "integer"
          },
          "user_id": {
            "required": false,
            "type": "integer"
          },
          "user_type": {
            "required": false,
            "type": "string"
          }
        }
      },
      "link": {
        "required": false,
        "type": "string"
      },
      "locked_date": {
        "required": false,
        "type": "integer"
      },
      "migrated_from": {
        "required": false,
        "type": "object",
        "properties": {
          "on_date": {
            "required": false,
            "type": "integer"
          },
          "other_site": {
            "required": false,
            "type": "object",
            "properties": {
              "aliases": {
                "required": false,
                "type": "array"
              },
              "api_site_parameter": {
                "required": false,
                "type": "string"
              },
              "audience": {
                "required": false,
                "type": "string"
              },
              "closed_beta_date": {
                "required": false,
                "type": "integer"
              },
              "favicon_url": {
                "required": false,
                "type": "string"
              },
              "high_resolution_icon_url": {
                "required": false,
                "type": "string"
              },
              "icon_url": {
                "required": false,
                "type": "string"
              },
              "launch_date": {
                "required": false,
                "type": "integer"
              },
              "logo_url": {
                "required": false,
                "type": "string"
              },
              "markdown_extensions": {
                "required": false,
                "type": "array"
              },
              "name": {
                "required": false,
                "type": "string"
              },
              "open_beta_date": {
                "required": false,
                "type": "integer"
              },
              "related_sites": {
                "required": false,
                "type": "array"
              },
              "site_state": {
                "required": false,
                "type": "string"
              },
              "site_type": {
                "required": false,
                "type": "string"
              },
              "site_url": {
                "required": false,
                "type": "string"
              },
              "styling": {
                "required": false,
                "type": "object",
                "properties": {
                  "link_color": {
                    "required": false,
                    "type": "string"
                  },
                  "tag_background_color": {
                    "required": false,
                    "type": "string"
                  },
                  "tag_foreground_color": {
                    "required": false,
                    "type": "string"
                  }
                }
              },
              "twitter_account": {
                "required": false,
                "type": "string"
              }
            }
          },
          "question_id": {
            "required": false,
            "type": "integer"
          }
        }
      },
      "migrated_to": {
        "required": false,
        "type": "object",
        "properties": {
          "on_date": {
            "required": false,
            "type": "integer"
          },
          "other_site": {
            "required": false,
            "type": "object",
            "properties": {
              "aliases": {
                "required": false,
                "type": "array"
              },
              "api_site_parameter": {
                "required": false,
                "type": "string"
              },
              "audience": {
                "required": false,
                "type": "string"
              },
              "closed_beta_date": {
                "required": false,
                "type": "integer"
              },
              "favicon_url": {
                "required": false,
                "type": "string"
              },
              "high_resolution_icon_url": {
                "required": false,
                "type": "string"
              },
              "icon_url": {
                "required": false,
                "type": "string"
              },
              "launch_date": {
                "required": false,
                "type": "integer"
              },
              "logo_url": {
                "required": false,
                "type": "string"
              },
              "markdown_extensions": {
                "required": false,
                "type": "array"
              },
              "name": {
                "required": false,
                "type": "string"
              },
              "open_beta_date": {
                "required": false,
                "type": "integer"
              },
              "related_sites": {
                "required": false,
                "type": "array"
              },
              "site_state": {
                "required": false,
                "type": "string"
              },
              "site_type": {
                "required": false,
                "type": "string"
              },
              "site_url": {
                "required": false,
                "type": "string"
              },
              "styling": {
                "required": false,
                "type": "object",
                "properties": {
                  "link_color": {
                    "required": false,
                    "type": "string"
                  },
                  "tag_background_color": {
                    "required": false,
                    "type": "string"
                  },
                  "tag_foreground_color": {
                    "required": false,
                    "type": "string"
                  }
                }
              },
              "twitter_account": {
                "required": false,
                "type": "string"
              }
            }
          },
          "question_id": {
            "required": false,
            "type": "integer"
          }
        }
      },
      "notice": {
        "required": false,
        "type": "object",
        "properties": {
          "body": {
            "required": false,
            "type": "string"
          },
          "creation_date": {
            "required": false,
            "type": "integer"
          },
          "owner_user_id": {
            "required": false,
            "type": "integer"
          }
        }
      },
      "owner": {
        "required": false,
        "type": "object",
        "properties": {
          "accept_rate": {
            "required": false,
            "type": "integer"
          },
          "badge_counts": {
            "required": false,
            "type": "object",
            "properties": {
              "bronze": {
                "required": false,
                "type": "integer"
              },
              "gold": {
                "required": false,
                "type": "integer"
              },
              "silver": {
                "required": false,
                "type": "integer"
              }
            }
          },
          "display_name": {
            "required": false,
            "type": "string"
          },
          "link": {
            "required": false,
            "type": "string"
          },
          "profile_image": {
            "required": false,
            "type": "string"
          },
          "reputation": {
            "required": false,
            "type": "integer"
          },
          "user_id": {
            "required": false,
            "type": "integer"
          },
          "user_type": {
            "required": false,
            "type": "string"
          }
        }
      },
      "protected_date": {
        "required": false,
        "type": "integer"
      },
      "question_id": {
        "required": false,
        "type": "integer"
      },
      "reopen_vote_count": {
        "required": false,
        "type": "integer"
      },
      "score": {
        "required": false,
        "type": "integer"
      },
      "share_link": {
        "required": false,
        "type": "string"
      },
      "tags": {
        "required": false,
        "type": "array"
      },
      "title": {
        "required": false,
        "type": "string"
      },
      "up_vote_count": {
        "required": false,
        "type": "integer"
      },
      "upvoted": {
        "required": false,
        "type": "boolean"
      },
      "view_count": {
        "required": false,
        "type": "integer"
      }
    }
  }
}

=== raml-apis/StackExchange/examples/questions.json
[
  {
    "accepted_answer_id": 1,
    "answer_count": 1,
    "answers": [
    ],
    "body": "some string",
    "body_markdown": "some string",
    "bounty_amount": 1,
    "bounty_closes_date": 1,
    "bounty_user": {
      "accept_rate": 1,
      "badge_counts": {
        "bronze": 1,
        "gold": 1,
        "silver": 1
      },
      "display_name": "some string",
      "link": "some string",
      "profile_image": "some string",
      "reputation": 1,
      "user_id": 1,
      "user_type": "some string"
    },
    "can_close": true,
    "can_flag": true,
    "close_vote_count": 1,
    "closed_date": 1,
    "closed_details": {
      "by_users": [
      ],
      "description": "some string",
      "on_hold": true,
      "original_questions": [
      ],
      "reason": "some string"
    },
    "closed_reason": "some string",
    "comment_count": 1,
    "comments": [
    ],
    "community_owned_date": 1,
    "creation_date": 1,
    "delete_vote_count": 1,
    "down_vote_count": 1,
    "downvoted": true,
    "favorite_count": 1,
    "favorited": true,
    "is_answered": true,
    "last_activity_date": 1,
    "last_edit_date": 1,
    "last_editor": {
      "accept_rate": 1,
      "badge_counts": {
        "bronze": 1,
        "gold": 1,
        "silver": 1
      },
      "display_name": "some string",
      "link": "some string",
      "profile_image": "some string",
      "reputation": 1,
      "user_id": 1,
      "user_type": "some string"
    },
    "link": "some string",
    "locked_date": 1,
    "migrated_from": {
      "on_date": 1,
      "other_site": {
        "aliases": [
        ],
        "api_site_parameter": "some string",
        "audience": "some string",
        "closed_beta_date": 1,
        "favicon_url": "some string",
        "high_resolution_icon_url": "some string",
        "icon_url": "some string",
        "launch_date": 1,
        "logo_url": "some string",
        "markdown_extensions": [
        ],
        "name": "some string",
        "open_beta_date": 1,
        "related_sites": [
        ],
        "site_state": "some string",
        "site_type": "some string",
        "site_url": "some string",
        "styling": {
          "link_color": "some string",
          "tag_background_color": "some string",
          "tag_foreground_color": "some string"
        },
        "twitter_account": "some string"
      },
      "question_id": 1
    },
    "migrated_to": {
      "on_date": 1,
      "other_site": {
        "aliases": [
        ],
        "api_site_parameter": "some string",
        "audience": "some string",
        "closed_beta_date": 1,
        "favicon_url": "some string",
        "high_resolution_icon_url": "some string",
        "icon_url": "some string",
        "launch_date": 1,
        "logo_url": "some string",
        "markdown_extensions": [
        ],
        "name": "some string",
        "open_beta_date": 1,
        "related_sites": [
        ],
        "site_state": "some string",
        "site_type": "some string",
        "site_url": "some string",
        "styling": {
          "link_color": "some string",
          "tag_background_color": "some string",
          "tag_foreground_color": "some string"
        },
        "twitter_account": "some string"
      },
      "question_id": 1
    },
    "notice": {
      "body": "some string",
      "creation_date": 1,
      "owner_user_id": 1
    },
    "owner": {
      "accept_rate": 1,
      "badge_counts": {
        "bronze": 1,
        "gold": 1,
        "silver": 1
      },
      "display_name": "some string",
      "link": "some string",
      "profile_image": "some string",
      "reputation": 1,
      "user_id": 1,
      "user_type": "some string"
    },
    "protected_date": 1,
    "question_id": 1,
    "reopen_vote_count": 1,
    "score": 1,
    "share_link": "some string",
    "tags": [
    ],
    "title": "some string",
    "up_vote_count": 1,
    "upvoted": true,
    "view_count": 1
  }
]
