=== raml-apis/StackExchange/schemas/question_timeline_events.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "comment_id": {
        "required": false,
        "type": "integer"
      },
      "creation_date": {
        "required": false,
        "type": "integer"
      },
      "down_vote_count": {
        "required": false,
        "type": "integer"
      },
      "owner": {
        "required": false,
        "type": "object",
        "properties": {
          "accept_rate": {
            "required": false,
            "type": "integer"
          },
          "badge_counts": {
            "required": false,
            "type": "object",
            "properties": {
              "bronze": {
                "required": false,
                "type": "integer"
              },
              "gold": {
                "required": false,
                "type": "integer"
              },
              "silver": {
                "required": false,
                "type": "integer"
              }
            }
          },
          "display_name": {
            "required": false,
            "type": "string"
          },
          "link": {
            "required": false,
            "type": "string"
          },
          "profile_image": {
            "required": false,
            "type": "string"
          },
          "reputation": {
            "required": false,
            "type": "integer"
          },
          "user_id": {
            "required": false,
            "type": "integer"
          },
          "user_type": {
            "required": false,
            "type": "string"
          }
        }
      },
      "post_id": {
        "required": false,
        "type": "integer"
      },
      "question_id": {
        "required": false,
        "type": "integer"
      },
      "revision_guid": {
        "required": false,
        "type": "string"
      },
      "timeline_type": {
        "required": false,
        "type": "string"
      },
      "up_vote_count": {
        "required": false,
        "type": "integer"
      },
      "user": {
        "required": false,
        "type": "object",
        "properties": {
          "accept_rate": {
            "required": false,
            "type": "integer"
          },
          "badge_counts": {
            "required": false,
            "type": "object",
            "properties": {
              "bronze": {
                "required": false,
                "type": "integer"
              },
              "gold": {
                "required": false,
                "type": "integer"
              },
              "silver": {
                "required": false,
                "type": "integer"
              }
            }
          },
          "display_name": {
            "required": false,
            "type": "string"
          },
          "link": {
            "required": false,
            "type": "string"
          },
          "profile_image": {
            "required": false,
            "type": "string"
          },
          "reputation": {
            "required": false,
            "type": "integer"
          },
          "user_id": {
            "required": false,
            "type": "integer"
          },
          "user_type": {
            "required": false,
            "type": "string"
          }
        }
      }
    }
  }
}

=== raml-apis/StackExchange/examples/question_timeline_events.json
[
  {
    "comment_id": 1,
    "creation_date": 1,
    "down_vote_count": 1,
    "owner": {
      "accept_rate": 1,
      "badge_counts": {
        "bronze": 1,
        "gold": 1,
        "silver": 1
      },
      "display_name": "some string",
      "link": "some string",
      "profile_image": "some string",
      "reputation": 1,
      "user_id": 1,
      "user_type": "some string"
    },
    "post_id": 1,
    "question_id": 1,
    "revision_guid": "some string",
    "timeline_type": "some string",
    "up_vote_count": 1,
    "user": {
      "accept_rate": 1,
      "badge_counts": {
        "bronze": 1,
        "gold": 1,
        "silver": 1
      },
      "display_name": "some string",
      "link": "some string",
      "profile_image": "some string",
      "reputation": 1,
      "user_id": 1,
      "user_type": "some string"
    }
  }
]
