=== raml-apis/StackExchange/schemas/revisions.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "body": {
        "required": false,
        "type": "string"
      },
      "comment": {
        "required": false,
        "type": "string"
      },
      "creation_date": {
        "required": false,
        "type": "integer"
      },
      "is_rollback": {
        "required": false,
        "type": "boolean"
      },
      "last_body": {
        "required": false,
        "type": "string"
      },
      "last_tags": {
        "required": false,
        "type": "array"
      },
      "last_title": {
        "required": false,
        "type": "string"
      },
      "post_id": {
        "required": false,
        "type": "integer"
      },
      "post_type": {
        "required": false,
        "type": "string"
      },
      "revision_guid": {
        "required": false,
        "type": "string"
      },
      "revision_number": {
        "required": false,
        "type": "integer"
      },
      "revision_type": {
        "required": false,
        "type": "string"
      },
      "set_community_wiki": {
        "required": false,
        "type": "boolean"
      },
      "tags": {
        "required": false,
        "type": "array"
      },
      "title": {
        "required": false,
        "type": "string"
      },
      "user": {
        "required": false,
        "type": "object",
        "properties": {
          "accept_rate": {
            "required": false,
            "type": "integer"
          },
          "badge_counts": {
            "required": false,
            "type": "object",
            "properties": {
              "bronze": {
                "required": false,
                "type": "integer"
              },
              "gold": {
                "required": false,
                "type": "integer"
              },
              "silver": {
                "required": false,
                "type": "integer"
              }
            }
          },
          "display_name": {
            "required": false,
            "type": "string"
          },
          "link": {
            "required": false,
            "type": "string"
          },
          "profile_image": {
            "required": false,
            "type": "string"
          },
          "reputation": {
            "required": false,
            "type": "integer"
          },
          "user_id": {
            "required": false,
            "type": "integer"
          },
          "user_type": {
            "required": false,
            "type": "string"
          }
        }
      }
    }
  }
}

=== raml-apis/StackExchange/examples/revisions.json
[
  {
    "body": "some string",
    "comment": "some string",
    "creation_date": 1,
    "is_rollback": true,
    "last_body": "some string",
    "last_tags": [
    ],
    "last_title": "some string",
    "post_id": 1,
    "post_type": "some string",
    "revision_guid": "some string",
    "revision_number": 1,
    "revision_type": "some string",
    "set_community_wiki": true,
    "tags": [
    ],
    "title": "some string",
    "user": {
      "accept_rate": 1,
      "badge_counts": {
        "bronze": 1,
        "gold": 1,
        "silver": 1
      },
      "display_name": "some string",
      "link": "some string",
      "profile_image": "some string",
      "reputation": 1,
      "user_id": 1,
      "user_type": "some string"
    }
  }
]
