=== raml-apis/StackExchange/schemas/suggested-edits.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": false,
  "type": "array",
  "items": {
    "required": false,
    "type": "object",
    "properties": {
      "approval_date": {
        "required": false,
        "type": "integer"
      },
      "body": {
        "required": false,
        "type": "string"
      },
      "comment": {
        "required": false,
        "type": "string"
      },
      "creation_date": {
        "required": false,
        "type": "integer"
      },
      "post_id": {
        "required": false,
        "type": "integer"
      },
      "post_type": {
        "required": false,
        "type": "string"
      },
      "proposing_user": {
        "required": false,
        "type": "object",
        "properties": {
          "accept_rate": {
            "required": false,
            "type": "integer"
          },
          "badge_counts": {
            "required": false,
            "type": "object",
            "properties": {
              "bronze": {
                "required": false,
                "type": "integer"
              },
              "gold": {
                "required": false,
                "type": "integer"
              },
              "silver": {
                "required": false,
                "type": "integer"
              }
            }
          },
          "display_name": {
            "required": false,
            "type": "string"
          },
          "link": {
            "required": false,
            "type": "string"
          },
          "profile_image": {
            "required": false,
            "type": "string"
          },
          "reputation": {
            "required": false,
            "type": "integer"
          },
          "user_id": {
            "required": false,
            "type": "integer"
          },
          "user_type": {
            "required": false,
            "type": "string"
          }
        }
      },
      "rejection_date": {
        "required": false,
        "type": "integer"
      },
      "suggested_edit_id": {
        "required": false,
        "type": "integer"
      },
      "tags": {
        "required": false,
        "type": "array"
      },
      "title": {
        "required": false,
        "type": "string"
      }
    }
  }
}

=== raml-apis/StackExchange/examples/suggested-edits.json
[
  {
    "approval_date": 1,
    "body": "some string",
    "comment": "some string",
    "creation_date": 1,
    "post_id": 1,
    "post_type": "some string",
    "proposing_user": {
      "accept_rate": 1,
      "badge_counts": {
        "bronze": 1,
        "gold": 1,
        "silver": 1
      },
      "display_name": "some string",
      "link": "some string",
      "profile_image": "some string",
      "reputation": 1,
      "user_id": 1,
      "user_type": "some string"
    },
    "rejection_date": 1,
    "suggested_edit_id": 1,
    "tags": [
    ],
    "title": "some string"
  }
]
